matrix:
  fast_finish: true
shallow_clone: true
environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    PlatformToolset: v142
    WindowsTargetPlatformVersion: 10.0.17763.0
    queryextents: queryextentsandrefcounts
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    PlatformToolset: v141
    WindowsTargetPlatformVersion: 10.0.14393.0
    queryextents: queryextents
platform:
- x64
- x86
- ARM64
configuration:
- Debug
- Release
for:
-
  matrix:
    only:
      - platform: ARM64
  test: off
build_script:
  - cmd: msbuild /nologo %Project% /verbosity:minimal /p:Platform=%Platform% /p:Configuration=%Configuration% /p:PlatformToolset=%PlatformToolset% /p:WindowsTargetPlatformVersion=%WindowsTargetPlatformVersion%
before_test:
  - ps: 'Initialize-Disk -Number (New-VHD -Path C:\test.vhdx -SizeBytes 127GB | Mount-VHD -Passthru).DiskNumber -PartitionStyle MBR -PassThru | New-Partition -UseMaximumSize -DriveLetter D | Format-Volume -FileSystem ReFS -Confirm:$false -Force'
test_script:
- cmd: |
    fsutil file createnew D:\test1 85899345920
    fsutil file setvaliddata D:\test1 85899345920
    fsutil file %queryextents% D:\test1
    if "%Platform%"=="x86" (%Configuration%\reflink.exe D:\test1 D:\test2) else (%Platform%\%Configuration%\reflink.exe D:\test1 D:\test2)
    fsutil file %queryextents% D:\test1
    fsutil file %queryextents% D:\test2
    dd if=C:\Windows\System32\ntdll.dll of=D:\test2 bs=1M oflag=seek_bytes seek=1G conv=notrunc
- ps: 'Dismount-VHD C:\test.vhdx -Passthru | Mount-VHD'
- cmd: |
    fsutil file %queryextents% D:\test1
    fsutil file %queryextents% D:\test2
deploy: off
