image: Visual Studio 2017
clone_depth: 1
environment:
  PATH: 'C:\msys64\mingw64\bin;C:\msys64\usr\bin;%PATH%'
  matrix:
  - Platform: x64
    CXXFLAGS: --target=x86_64-windows
  - Platform: x64_x86
    CXXFLAGS: --target=i386-windows
  - Platform: x64_arm64
    CXXFLAGS: --target=arm64-windows
matrix:
  allow_failures:
    - Platform: x64_arm64
build_script:
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" %Platform%
  - make -B
test: off
deploy: off